2018-05-22 23:12:23,394 INFO: Microblog startup [in /Users/marthareese/microblog/app/__init__.py:24]
2018-05-22 23:14:00,003 INFO: Microblog startup [in /Users/marthareese/microblog/app/__init__.py:24]
2018-05-22 23:14:04,732 ERROR: Exception on /index [GET] [in /Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/marthareese/microblog/app/routes.py", line 21, in index
    raise Exception('Message')
Exception: Message
2018-05-22 23:15:05,483 INFO: Microblog startup [in /Users/marthareese/microblog/app/__init__.py:24]
2018-05-22 23:15:08,685 CRITICAL: ohnoes [in /Users/marthareese/microblog/app/routes.py:21]
2018-05-22 23:15:08,695 ERROR: Exception on /index [GET] [in /Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/marthareese/microblog/newvenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/marthareese/microblog/app/routes.py", line 22, in index
    raise Exception('Message')
Exception: Message
2018-05-22 23:17:12,906 INFO: Microblog startup [in /Users/marthareese/microblog/app/__init__.py:24]
2018-05-22 23:20:16,021 INFO: Microblog startup [in /Users/marthareese/microblog/app/__init__.py:36]
2018-05-22 23:20:53,763 INFO: Microblog startup [in /Users/marthareese/microblog/app/__init__.py:34]
